"""
Interactive Map Visualization for Aerial Photography Coordinates

This script reads coordinate estimates from all processed items and displays them
on an interactive Folium map. The map includes markers with popups showing metadata
about each photograph.

Usage:
    python utilities/visualize_coordinates.py [--output map.html] [--exclude-low-confidence]

Requirements:
    - folium package installed
    - Coordinate files generated by llm_coordinates.py

Output:
    An HTML file with an interactive map that can be opened in any web browser.
"""

import json
import argparse
import base64
import logging
from pathlib import Path
from dataclasses import dataclass
from typing import Optional

import folium
from folium.plugins import MarkerCluster

# Default paths
PROJECT_ROOT = Path(__file__).parent.parent
ITEMS_DIR = PROJECT_ROOT / "output" / "items"
DEFAULT_OUTPUT = PROJECT_ROOT / "output" / "coordinates_map.html"

# Long Island center point for default map view
LONG_ISLAND_CENTER = (40.8, -73.2)
DEFAULT_ZOOM = 9

# Marker colors based on confidence level
CONFIDENCE_COLORS = {
    "high": "green",
    "medium": "orange",
    "low": "red",
    "none": "gray"
}

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger(__name__)


@dataclass
class MapPoint:
    """Represents a point to display on the map."""
    item_id: str
    item_dir: Path
    latitude: float
    longitude: float
    confidence: str
    reasoning: str
    coverage: str
    description: str
    excluded: bool = False
    thumbnail_base64: str = ""


def load_thumbnail_base64(item_dir: Path) -> str:
    """Load and encode the thumbnail image as base64.

    Args:
        item_dir: Path to the item directory.

    Returns:
        Base64-encoded image string, or empty string if not found.
    """
    thumbnail_path = item_dir / "image_thumbnail.jpg"
    if not thumbnail_path.exists():
        return ""

    try:
        with open(thumbnail_path, "rb") as f:
            image_data = f.read()
        return base64.b64encode(image_data).decode("utf-8")
    except Exception as e:
        logger.warning(f"Error loading thumbnail {thumbnail_path}: {e}")
        return ""


def load_coordinates(items_dir: Path) -> list[MapPoint]:
    """Load all coordinate files from the items directory.

    Args:
        items_dir: Path to the items directory.

    Returns:
        List of MapPoint objects with valid coordinates.
    """
    points = []

    item_dirs = sorted([
        d for d in items_dir.iterdir()
        if d.is_dir() and (d / "coordinates.json").exists()
    ])

    for item_dir in item_dirs:
        coord_file = item_dir / "coordinates.json"

        try:
            with open(coord_file, "r") as f:
                data = json.load(f)

            # Skip items without coordinates
            if data.get("latitude") is None or data.get("longitude") is None:
                continue

            # Load thumbnail as base64
            thumbnail_base64 = load_thumbnail_base64(item_dir)

            point = MapPoint(
                item_id=item_dir.name,
                item_dir=item_dir,
                latitude=data["latitude"],
                longitude=data["longitude"],
                confidence=data.get("confidence", "none"),
                reasoning=data.get("reasoning", ""),
                coverage=data.get("source_coverage", ""),
                description=data.get("source_description", ""),
                excluded=data.get("excluded", False),
                thumbnail_base64=thumbnail_base64
            )
            points.append(point)

        except (json.JSONDecodeError, KeyError) as e:
            logger.warning(f"Error reading {coord_file}: {e}")
            continue

    return points


def create_popup_html(point: MapPoint) -> str:
    """Create HTML content for a marker popup.

    Args:
        point: MapPoint object with coordinate data.

    Returns:
        HTML string for the popup.
    """
    # Truncate long descriptions
    description = point.description
    if len(description) > 200:
        description = description[:200] + "..."

    coverage = point.coverage
    if len(coverage) > 100:
        coverage = coverage[:100] + "..."

    excluded_badge = ""
    if point.excluded:
        excluded_badge = '<span style="color: red; font-weight: bold;">[EXCLUDED]</span><br>'

    # Create thumbnail HTML if available
    thumbnail_html = ""
    if point.thumbnail_base64:
        thumbnail_html = f"""
        <div style="margin-bottom: 10px; text-align: center;">
            <img src="data:image/jpeg;base64,{point.thumbnail_base64}"
                 style="max-width: 280px; max-height: 200px; border: 1px solid #ccc; border-radius: 4px;"
                 alt="Aerial photograph thumbnail">
        </div>
        """

    html = f"""
    <div style="width: 300px; font-family: Arial, sans-serif;">
        <h4 style="margin: 0 0 8px 0; color: #333;">{point.item_id}</h4>
        {excluded_badge}
        {thumbnail_html}
        <p style="margin: 4px 0;"><strong>Confidence:</strong>
            <span style="color: {CONFIDENCE_COLORS.get(point.confidence, 'gray')};">
                {point.confidence.upper()}
            </span>
        </p>
        <p style="margin: 4px 0;"><strong>Coordinates:</strong><br>
            {point.latitude:.6f}, {point.longitude:.6f}
        </p>
        <p style="margin: 4px 0;"><strong>Coverage:</strong><br>
            <em>{coverage or 'N/A'}</em>
        </p>
        <p style="margin: 4px 0;"><strong>Description:</strong><br>
            <em>{description or 'N/A'}</em>
        </p>
        <p style="margin: 4px 0;"><strong>Reasoning:</strong><br>
            {point.reasoning or 'N/A'}
        </p>
    </div>
    """
    return html


def create_map(
    points: list[MapPoint],
    exclude_low_confidence: bool = False,
    exclude_outside_bounds: bool = True,
    use_clustering: bool = True
) -> folium.Map:
    """Create a Folium map with markers for all coordinate points.

    Args:
        points: List of MapPoint objects.
        exclude_low_confidence: If True, exclude points with 'low' confidence.
        exclude_outside_bounds: If True, exclude points marked as outside Long Island.
        use_clustering: If True, group nearby markers into clusters.

    Returns:
        Folium Map object.
    """
    # Filter points based on options
    filtered_points = points
    if exclude_low_confidence:
        filtered_points = [p for p in filtered_points if p.confidence != "low"]
    if exclude_outside_bounds:
        filtered_points = [p for p in filtered_points if not p.excluded]

    logger.info(f"Displaying {len(filtered_points)} of {len(points)} points")

    # Create base map
    m = folium.Map(
        location=LONG_ISLAND_CENTER,
        zoom_start=DEFAULT_ZOOM,
        tiles="OpenStreetMap"
    )

    # Add alternative tile layers
    folium.TileLayer("CartoDB positron", name="Light").add_to(m)
    folium.TileLayer("CartoDB dark_matter", name="Dark").add_to(m)
    folium.TileLayer(
        tiles="https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",
        attr="Esri",
        name="Satellite"
    ).add_to(m)

    # Create marker cluster if enabled
    if use_clustering:
        marker_group = MarkerCluster(name="Coordinates")
    else:
        marker_group = folium.FeatureGroup(name="Coordinates")

    # Add markers for each point
    for point in filtered_points:
        color = CONFIDENCE_COLORS.get(point.confidence, "gray")
        if point.excluded:
            color = "black"

        popup_html = create_popup_html(point)

        folium.Marker(
            location=[point.latitude, point.longitude],
            popup=folium.Popup(popup_html, max_width=350),
            tooltip=f"{point.item_id} ({point.confidence})",
            icon=folium.Icon(color=color, icon="camera", prefix="fa")
        ).add_to(marker_group)

    marker_group.add_to(m)

    # Add layer control
    folium.LayerControl().add_to(m)

    # Add legend
    legend_html = """
    <div style="
        position: fixed;
        bottom: 50px;
        left: 50px;
        z-index: 1000;
        background-color: white;
        padding: 10px;
        border: 2px solid gray;
        border-radius: 5px;
        font-family: Arial, sans-serif;
        font-size: 12px;
    ">
        <strong>Confidence Level</strong><br>
        <i class="fa fa-map-marker" style="color: green;"></i> High<br>
        <i class="fa fa-map-marker" style="color: orange;"></i> Medium<br>
        <i class="fa fa-map-marker" style="color: red;"></i> Low<br>
        <i class="fa fa-map-marker" style="color: black;"></i> Excluded
    </div>
    """
    m.get_root().html.add_child(folium.Element(legend_html))

    return m


def main():
    """Main entry point for the script."""
    parser = argparse.ArgumentParser(
        description="Visualize coordinate estimates on an interactive map"
    )
    parser.add_argument(
        "--output", "-o",
        type=Path,
        default=DEFAULT_OUTPUT,
        help=f"Output HTML file path (default: {DEFAULT_OUTPUT})"
    )
    parser.add_argument(
        "--items-dir",
        type=Path,
        default=ITEMS_DIR,
        help=f"Path to items directory (default: {ITEMS_DIR})"
    )
    parser.add_argument(
        "--exclude-low-confidence",
        action="store_true",
        help="Exclude points with low confidence"
    )
    parser.add_argument(
        "--include-excluded",
        action="store_true",
        help="Include points that were marked as outside Long Island bounds"
    )
    parser.add_argument(
        "--no-clustering",
        action="store_true",
        help="Disable marker clustering (show all markers individually)"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Enable verbose logging"
    )

    args = parser.parse_args()

    if args.verbose:
        logging.getLogger().setLevel(logging.DEBUG)

    # Load coordinates
    if not args.items_dir.exists():
        logger.error(f"Items directory not found: {args.items_dir}")
        return 1

    logger.info(f"Loading coordinates from {args.items_dir}")
    points = load_coordinates(args.items_dir)
    logger.info(f"Found {len(points)} items with coordinates")

    if not points:
        logger.warning("No coordinate data found. Run llm_coordinates.py first.")
        return 1

    # Create map
    m = create_map(
        points,
        exclude_low_confidence=args.exclude_low_confidence,
        exclude_outside_bounds=not args.include_excluded,
        use_clustering=not args.no_clustering
    )

    # Ensure output directory exists
    args.output.parent.mkdir(parents=True, exist_ok=True)

    # Save map
    m.save(str(args.output))
    logger.info(f"Map saved to {args.output}")
    logger.info(f"Open in browser: file://{args.output.absolute()}")

    return 0


if __name__ == "__main__":
    exit(main())
